name: namer_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  google_fonts: ^6.2.0
  localstorage: ^4.0.0+1
  sqflite: ^2.3.2
  path: ^1.8.3
  floor: ^1.4.2
  internet_connection_checker: ^0.0.1+4
  connectivity_plus: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^1.4.2
  build_runner: ^2.1.2

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true